import keyboard
from tkinter import *

root = Tk()
root.title("hot-key-board")

btnQ = Button(root, text = 'Q', bd = '5')
btnW = Button(root, text = 'W', bd = '5')
btnE = Button(root, text = 'E', bd = '5')
btnR = Button(root, text = 'R', bd = '5')
btnT = Button(root, text = 'T', bd = '5')
btnY = Button(root, text = 'Y', bd = '5')
btnU = Button(root, text = 'U', bd = '5')
btnI = Button(root, text = 'I', bd = '5')
btnO = Button(root, text = 'O', bd = '5')
btnP = Button(root, text = 'P', bd = '5')
btnA = Button(root, text = 'A', bd = '5')
btnS = Button(root, text = 'S', bd = '5')
btnD = Button(root, text = 'D', bd = '5')
btnF = Button(root, text = 'F', bd = '5')
btnG = Button(root, text = 'G', bd = '5')
btnH = Button(root, text = 'H', bd = '5')
btnJ = Button(root, text = 'J', bd = '5')
btnK = Button(root, text = 'K', bd = '5')
btnL = Button(root, text = 'L', bd = '5')
btnZ = Button(root, text = 'Z', bd = '5')
btnX = Button(root, text = 'X', bd = '5')
btnC = Button(root, text = 'C', bd = '5')
btnV = Button(root, text = 'V', bd = '5')
btnB = Button(root, text = 'B', bd = '5')
btnN = Button(root, text = 'N', bd = '5')
btnM = Button(root, text = 'M', bd = '5')
btnQ.pack()
btnW.pack()
btnE.pack()
btnR.pack()
btnT.pack()
btnY.pack()
btnU.pack()
btnI.pack()
btnO.pack()
btnP.pack()
btnA.pack()
btnS.pack()
btnD.pack()
btnF.pack()
btnG.pack()
btnH.pack()
btnJ.pack()
btnK.pack()
btnL.pack()
btnZ.pack()
btnX.pack()
btnC.pack()
btnV.pack()
btnB.pack()
btnN.pack()
btnM.pack()

mainloop()